[package]
name = "eggcc"
version = "0.1.0"
edition = "2021"

[[test]]
harness = false
name = "files"


[dependencies]
egglog = { git = "https://github.com/egraphs-good/egglog", rev = "c83fc75" }
log = "0.4.19"
thiserror = "1"
lalrpop-util = { version = "0.19.8", features = ["lexer"] }
petgraph = "0.6"
hashbrown = "0.14"
indexmap = "2.0"
fixedbitset = "0.4.2"

bril2json = { path = "bril/bril-rs/bril2json" }
brilirs = { path = "bril/brilirs" }
bril-rs = { path = "bril/bril-rs" }
ordered-float = { version = "3.7" }
serde_json = "1.0.103"

# binary dependencies
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
glob = "0.3.1"
libtest-mimic = "0.6.1"
insta = { version = "1.31.0", features = ["yaml"] }


[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
