[package]
name = "eggcc"
version = "0.1.0"
edition = "2021"

[[test]]
harness = false
name = "files"


[dependencies]
egglog = { git = "https://github.com/oflatt/egg-smol", rev = "a2cf814a91dd98509903e3c744b513f99f96413b" }
log = "0.4.19"
thiserror = "1"
lalrpop-util = {version = "0.19.8", features = ["lexer"]}

bril2json = { git = "https://github.com/sampsyo/bril", rev = "1095460" }
bril-rs = { git = "https://github.com/sampsyo/bril", rev = "1095460", required-features = ["ssa"]}

[dev-dependencies]
glob = "0.3.1"
libtest-mimic = "0.6.1"
insta = { version = "1.31.0", features = ["yaml"] }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3