name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: Swatinem/rust-cache@v2
    - run: |
        set -e
        sudo apt install graphviz 
        ./install_ubuntu.sh
        cargo install cargo-insta
        make runtime
        make test
  nits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: Swatinem/rust-cache@v2
    - run: make nits
  