name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: Swatinem/rust-cache@v2
    - run: sudo apt install graphviz 
    - run: ./install_ubuntu.sh
    - run: cargo install cargo-insta
    - run: make runtime
    - run: make test
  nits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - uses: Swatinem/rust-cache@v2
    - run: ./install_ubuntu.sh
    - run: make nits
  